site_name: Markdown Refdocs
nav:
  - Home: index.md
  - Reference:
      - markdown_refdocs.main: reference/markdown_refdocs/main.md
      - markdown_refdocs.parsers: reference/markdown_refdocs/parsers.md
      - markdown_refdocs.markdown: reference/markdown_refdocs/markdown.md
markdown_extensions:
  - codehilite
theme:
  name: "material"
repo_url: https://github.com/creisle/markdown_refdocs.git
site_dir: build-docs
