name: Deploy the static file to GitHub Page
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: checkout
      uses: actions/checkout@v1
    
    - name: install and build
      run: |
        python3 -m pip install --upgrade pip setuptools
        pip install .[docs]
        markdown_refdocs markdown_refdocs -o docs/reference
        mkdocs build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build-docs
